Rails:
  Enabled: true

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - 'bin/*'
    - '*/vendor//'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/initializers/*'
    - 'config/environments/*'
    - 'lib/tasks/populate.rake'
    - 'config/routes.rb'
    - 'spec/*'
    - 'spec/*/*'
    - 'spec/*/*/*'
    - 'spec/*/*/*/*'

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: true
